import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { renameSync, existsSync } from 'fs';
import CssModulesPlugin from 'esbuild-css-modules-plugin';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/** Renames main.css → styles.css (Obsidian loads styles.css). */
const renameCssPlugin = {
	name: 'rename-css',
	setup(build) {
		build.onEnd(() => {
			if (existsSync('main.css')) {
				renameSync('main.css', 'styles.css');
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	plugins: [CssModulesPlugin(), renameCssPlugin],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}